import os
from django.db import models


def get_image_path_instrument1(instance):
    return os.path.join('uploads', 'instrument', str(instance.siteId.pk))


class Instrument(models.Model):
    id = models.AutoField(primary_key=True, help_text='autogenerated id')
    siteId = models.ForeignKey('climate.Site', blank=True, null=True, help_text='foreign key for Site table')
    title = models.CharField(max_length=100, unique=True, help_text='unique title of the instrument')
    comment = models.TextField(blank=True, help_text='any additional information')
    type = models.CharField(max_length=50,
                            help_text='manufacturer and type of the instrument (e.g. LaCrosse WS-3600)')
    isActive = models.BooleanField(default=True, help_text='is active')
    isDeleted = models.BooleanField(default=False, help_text='is_deleted')
    primaryImage = models.ImageField(upload_to=get_image_path_instrument1, blank=True, null=True,
                                     help_text='representative image of the instrument')
