from django.db import models


class RawData(models.Model):
    """
    | Raw data generated by automated weather station
    | Unique: sideId and createdDate together
    """
    class Meta:
        unique_together = (('siteId', 'createdDate'),)

    def __str__(self):
        return "RawData [siteId: {}, createdDate: {}]".format(self.siteId, self.createdDate)

    def __repr__(self):
        return self.__str__()

    siteId = models.ForeignKey('climate.Site', help_text='foreign key for Site table')
    createdDate = models.DateTimeField(help_text='timestamp')
    pressure = models.DecimalField(blank=True, null=True,
                                   max_digits=5, decimal_places=1,
                                   help_text='sea level air pressure (hPa)')
    tempIn = models.DecimalField(blank=True, null=True, max_digits=3, decimal_places=1,
                                 help_text='indoor temperature (°C)')
    humidityIn = models.DecimalField(blank=True, null=True, max_digits=3, decimal_places=1,
                                     help_text='indoor relative humidity (%)')
    temperature = models.DecimalField(blank=True, null=True, max_digits=3, decimal_places=1,
                                      help_text='temperature at 2m above ground level (°C)')
    humidity = models.DecimalField(blank=True, null=True, max_digits=3, decimal_places=1,
                                   help_text='relative humidity at 2m above ground level (°C)')
    dewpoint = models.DecimalField(blank=True, null=True, max_digits=3, decimal_places=1,
                                   help_text='dew point at 2m above ground level (°C)')
    windChill = models.DecimalField(blank=True, null=True, max_digits=3, decimal_places=1,
                                    help_text='human temperature feeling (°C)')
    windSpeed = models.DecimalField(blank=True, null=True, max_digits=4, decimal_places=1,
                                    help_text='wind speed at 10m above ground level (m/s)')
    windDir = models.DecimalField(blank=True, null=True, max_digits=4, decimal_places=1,
                                  help_text='wind direction in degrees')
    gust = models.DecimalField(blank=True, null=True, max_digits=4, decimal_places=1,
                               help_text='gust speed at 10m above ground level (m/s)')
    precipitation = models.DecimalField(blank=True, null=True, max_digits=4, decimal_places=1,
                                        help_text='precipitation amount in the current time step (mm)')
