import os
from django.db import models


def get_image_path_site1(instance, filename):
    return os.path.join('uploads', 'site', str(instance.id))


class Site(models.Model):
    NARROW_AREA = (
        (1, 'kert'),
        (2, 'parkoló'),
        (3, 'tető'),
        (4, 'udvar'),
        (5, 'füves terület'),
        (6, 'fás terület'),
        (7, 'vízpart'),
        (8, 'utca')
    )

    WIDE_AREA = (
        (1, 'belváros'),
        (2, 'kertváros'),
        (3, 'lakótelep'),
        (4, 'ipari terület'),
        (5, 'hegyvidék'),
        (6, 'vízpart'),
        (7, 'külterület')
    )

    id = models.AutoField(primary_key=True, help_text='autogenerated primary key')
    owner = models.ForeignKey('auth.user', help_text='key for auth.user table')
    title = models.CharField(max_length=100, unique=True, help_text='descriptive name of the site')
    comment = models.TextField(blank=True, help_text='any additional information in text')
    createdDate = models.DateTimeField(auto_now_add=True, help_text='datetime of creation')
    isActive = models.BooleanField(default=True, help_text='is active')
    isPublic = models.BooleanField(default=True, help_text='is public')
    isDeleted = models.BooleanField(default=False, help_text='is already deleted')
    lat = models.DecimalField(max_digits=20, decimal_places=15, help_text='geographical latitude')
    lon = models.DecimalField(max_digits=20, decimal_places=15, help_text='geographical longitude')
    narrowArea = models.IntegerField(choices=NARROW_AREA, default=1, help_text='enum Weather.NARROW_AREA')
    wideArea = models.IntegerField(choices=WIDE_AREA,
                                   default=1, help_text='enum Weather.WIDE_AREA')
    primaryImage = models.ImageField(upload_to=get_image_path_site1, blank=True, null=True,
                                     help_text='representative image of the site')

    def __str__(self):
        return self.title

    def get_wide_area(self):
        """
        | Get the name of the wide area around the site

        :return: name
        """
        find = [x[1] for x in Site.WIDE_AREA if x[0] == self.wideArea]
        if len(find) > 0:
            return find[0]

    def get_narrow_area(self):
        """
        | Get the name of the narrow area around the site

        :return: name
        """
        find = [x[1] for x in Site.NARROW_AREA if x[0] == self.narrowArea]
        if len(find) > 0:
            return find[0]
