version: '3'
services:
  app:
    build: .
    container_name: django_app
    user: django
    command: "./start0.sh"
    ports:
      - "3000:8000"
#    expose:
#      - "8000"
    volumes:
      - ./media:/app/media
      - ./.env:/app/.env:ro
    depends_on:
      - db
    networks:
      - web_network
      - db_network
    environment:
      - MYSQL_PORT=3306
  db:
    image: mysql:latest
    container_name: django_mysql
    user: ${CURRENT_UID}
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - "./mysql:/var/lib/mysql"
    ports: # TODO do not expose!
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret123
      - MYSQL_DATABASE=django
      - MYSQL_USER=django
      - MYSQL_PASSWORD=password
    networks:
      - db_network
#  nginx:
#    image: nginx
#    container_name: django_nginx
#    ports:
#      - "3000:8000"
#    volumes:
#      - ./climate/static:/app/static
#      - ./nginx_site.conf:/etc/nginx/conf.d/zivatar.conf
#    depends_on:
#      - app
#    networks:
#      - web_network

networks:
  web_network:
    driver: bridge
  db_network:
    driver: bridge

volumes:
  static-volume:
