version: '3'
services:
  app:
    build: .
    user: django
    #command: "./start0.sh"
    command: "gunicorn --timeout=30 --workers=2 --bind 0.0.0.0:8000 zivatar.wsgi:application"
    volumes:
      - ./media:/app/media
      - ./.env:/app/.env:ro
    depends_on:
      - db
    environment:
      - MYSQL_PORT=3306
  db:
    image: mysql:latest
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - "./mysql:/var/lib/mysql"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret123
      - MYSQL_DATABASE=django
      - MYSQL_USER=django
      - MYSQL_PASSWORD=password
  nginx:
    image: nginx
    ports:
      - "3000:8000"
    volumes:
      - ./climate/static:/app/static
      - ./nginx2.conf:/etc/nginx/conf.d/zivatar.conf
    depends_on:
      - app

volumes:
  static-volume:
