# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-04 19:36
from __future__ import unicode_literals

import climate.models.Instrument
import climate.models.Site
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('dataAvailable', models.IntegerField(default=0)),
                ('tempMin', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('tempMax', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('tempAvg', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('precipitation', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('precipHalfHour', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('tempDistribution', models.CommaSeparatedIntegerField(blank=True, max_length=200)),
                ('rhDistribution', models.CommaSeparatedIntegerField(blank=True, max_length=200)),
                ('windDistribution', models.CommaSeparatedIntegerField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('comment', models.TextField(blank=True)),
                ('type', models.CharField(max_length=50)),
                ('isActive', models.BooleanField(default=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('primaryImage', models.ImageField(blank=True, null=True, upload_to=climate.models.Instrument.get_image_path_instrument1)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('dataAvailable', models.IntegerField(default=0)),
                ('tempMin', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('tempMax', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('tempAvg', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('precipitation', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('tempMinAvg', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('tempMaxAvg', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('summerDays', models.IntegerField(blank=True, null=True)),
                ('frostDays', models.IntegerField(blank=True, null=True)),
                ('winterDays', models.IntegerField(blank=True, null=True)),
                ('coldDays', models.IntegerField(blank=True, null=True)),
                ('warmNights', models.IntegerField(blank=True, null=True)),
                ('warmDays', models.IntegerField(blank=True, null=True)),
                ('hotDays', models.IntegerField(blank=True, null=True)),
                ('tempDistribution', models.CommaSeparatedIntegerField(blank=True, max_length=200)),
                ('rhDistribution', models.CommaSeparatedIntegerField(blank=True, max_length=200)),
                ('windDistribution', models.CommaSeparatedIntegerField(blank=True, max_length=200)),
                ('significants', picklefield.fields.PickledObjectField(default={}, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canUpload', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateTimeField()),
                ('pressure', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('tempIn', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('humidityIn', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('humidity', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('dewpoint', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('windChill', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('windSpeed', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('windDir', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('gust', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('precipitation', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RawManualData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=-1)),
                ('month', models.IntegerField(default=-1)),
                ('day', models.IntegerField(default=-1)),
                ('tMin', models.FloatField(blank=True, null=True)),
                ('tMax', models.FloatField(blank=True, null=True)),
                ('precAmount', models.FloatField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('isSnow', models.BooleanField(default=False)),
                ('snowDepth', models.FloatField(default=0.0)),
                ('_weatherCode', models.CommaSeparatedIntegerField(blank=True, choices=[(1, 'füst'), (2, 'homály'), (3, 'párásság'), (4, 'köd'), (19, 'nyílt köd'), (13, 'homokvihar'), (14, 'porforgatag'), (5, '22-es halo'), (6, 'melléknap'), (7, 'érintő ív'), (8, 'ritkább halo'), (9, 'villámlás'), (10, 'dörgés'), (11, 'szivárvány'), (12, 'csapadéksáv'), (15, 'szitálás'), (16, 'szemcsés hó'), (17, 'ónos szitálás'), (34, 'ónos eső'), (18, 'eső'), (20, 'havazás'), (22, 'havas eső'), (24, 'zápor'), (25, 'hózápor'), (26, 'havas eső zápor'), (27, 'jégeső'), (29, 'tuba'), (30, 'tornádó'), (31, 'zivatar'), (32, 'hódara-zápor'), (33, 'fagyott eső'), (34, 'harmat'), (35, 'dér'), (36, 'zúzmara'), (37, 'hófúvás')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RawObservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True)),
                ('_weatherCode', models.CommaSeparatedIntegerField(blank=True, choices=[(1, 'füst'), (2, 'homály'), (3, 'párásság'), (4, 'köd'), (19, 'nyílt köd'), (13, 'homokvihar'), (14, 'porforgatag'), (5, '22-es halo'), (6, 'melléknap'), (7, 'érintő ív'), (8, 'ritkább halo'), (9, 'villámlás'), (10, 'dörgés'), (11, 'szivárvány'), (12, 'csapadéksáv'), (15, 'szitálás'), (16, 'szemcsés hó'), (17, 'ónos szitálás'), (34, 'ónos eső'), (18, 'eső'), (20, 'havazás'), (22, 'havas eső'), (24, 'zápor'), (25, 'hózápor'), (26, 'havas eső zápor'), (27, 'jégeső'), (29, 'tuba'), (30, 'tornádó'), (31, 'zivatar'), (32, 'hódara-zápor'), (33, 'fagyott eső'), (34, 'harmat'), (35, 'dér'), (36, 'zúzmara'), (37, 'hófúvás')], max_length=200)),
                ('windSpeed', models.IntegerField(choices=[(-1, 'nem észlelt'), (0, '0: szélcsend'), (1, '1: füst lengedezik'), (2, '2: arcon érezhető'), (3, '3: vékony gallyak mozognak'), (4, '4: kisebb ágak mozognak'), (5, '5: nagyobb ágak mozognak, suhog'), (6, '6: drótkötelek zúgnak, vastag ágak mozognak'), (7, '7: gallyak letörnek'), (8, '8: ágak letörnek'), (9, '9: gyengébb fák kidőlnek, épületekben kisebb károk'), (10, '10: fák gyökerestül kidőlnek'), (11, '11: súlyos károk'), (12, '12: súlyos pusztítás')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('comment', models.TextField(blank=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('isActive', models.BooleanField(default=True)),
                ('isPublic', models.BooleanField(default=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('lat', models.DecimalField(decimal_places=15, max_digits=20)),
                ('lon', models.DecimalField(decimal_places=15, max_digits=20)),
                ('narrowArea', models.IntegerField(choices=[(1, 'kert'), (2, 'parkoló'), (3, 'tető'), (4, 'udvar'), (5, 'füves terület'), (6, 'fás terület'), (7, 'vízpart'), (8, 'utca')], default=1)),
                ('wideArea', models.IntegerField(choices=[(1, 'belváros'), (2, 'kertváros'), (3, 'lakótelep'), (4, 'ipari terület'), (5, 'hegyvidék'), (6, 'vízpart'), (7, 'külterület')], default=1)),
                ('primaryImage', models.ImageField(blank=True, null=True, upload_to=climate.models.Site.get_image_path_site1)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UnprocessedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('uploaded_at', models.DateTimeField()),
                ('site_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climate.Site')),
            ],
        ),
        migrations.CreateModel(
            name='YearlyStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('significants', picklefield.fields.PickledObjectField(default={}, editable=False)),
                ('siteId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climate.Site')),
            ],
        ),
        migrations.AddField(
            model_name='rawobservation',
            name='siteId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climate.Site'),
        ),
        migrations.AddField(
            model_name='rawmanualdata',
            name='siteId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climate.Site'),
        ),
        migrations.AddField(
            model_name='rawdata',
            name='siteId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climate.Site'),
        ),
        migrations.AddField(
            model_name='monthlystatistics',
            name='siteId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climate.Site'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='siteId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='climate.Site'),
        ),
        migrations.AddField(
            model_name='dailystatistics',
            name='siteId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climate.Site'),
        ),
        migrations.AlterUniqueTogether(
            name='yearlystatistics',
            unique_together=set([('siteId', 'year')]),
        ),
        migrations.AlterUniqueTogether(
            name='rawmanualdata',
            unique_together=set([('year', 'month', 'day', 'siteId')]),
        ),
        migrations.AlterUniqueTogether(
            name='rawdata',
            unique_together=set([('siteId', 'createdDate')]),
        ),
        migrations.AlterUniqueTogether(
            name='monthlystatistics',
            unique_together=set([('year', 'month', 'siteId')]),
        ),
        migrations.AlterUniqueTogether(
            name='dailystatistics',
            unique_together=set([('siteId', 'year', 'month', 'day')]),
        ),
    ]
