# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-04 19:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unprocesseddata',
            name='site_id',
        ),
        migrations.DeleteModel(
            name='UnprocessedData',
        ),
    ]
