# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-04 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climate', '0002_auto_20180504_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnprocessedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('uploaded_at', models.DateTimeField()),
                ('site_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climate.Site')),
            ],
        ),
    ]
